name: smart_trip_planner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1  

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^3.0.0-dev.3
  cloud_firestore: ^6.0.0

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  firebase_storage: ^13.0.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  http: ^1.2.1
  dio: ^5.4.1
  json_annotation: ^4.8.1

  async: ^2.11.0

  url_launcher: ^6.3.2

  flutter_spinkit: ^5.2.0

  flutter_svg: ^2.0.10+1

  intl: ^0.20.2

  flutter_screenutil: ^5.9.0
  rename: ^3.1.0
  sensors_plus: ^6.1.1
  google_generative_ai: ^0.4.7
  font_awesome_flutter: ^10.8.0

  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  mockito: ^5.4.4
  http_mock_adapter: ^0.6.0+1

  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env
    - assets/images/
    - assets/animations/

  uses-material-design: true

flutter_native_splash:
  color: "#E8F5E9" # A pleasant light green background to match your theme
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
